language: ruby

before_install: gem update bundler

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.6
  - 2.3.3
  - 2.4.1
  - ruby-head
  - jruby-9.1.8.0
  - rbx-2

gemfile:
  - gemfiles/mongo_mapper.gemfile

sudo: false

services: mongodb

script: 'bundle exec rake test'

cache: bundler

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-9.1.8.0
    - rvm: rbx-2
  fast_finish: true
